# Generated by Django 5.1.1 on 2024-09-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_finder", "0002_review_is_google_review_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlocation",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
