# Generated by Django 5.1.1 on 2024-09-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_finder", "0004_foodlocation_icon_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodlocation",
            name="icon_url",
        ),
        migrations.AddField(
            model_name="foodlocation",
            name="photo_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
