# Generated by Django 5.1.1 on 2024-09-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_finder", "0005_remove_foodlocation_icon_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodlocation",
            name="photo_reference",
        ),
        migrations.AddField(
            model_name="foodlocation",
            name="photo_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
