# Generated by Django 5.1.1 on 2024-11-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_spotifywrapped_created_at_spotifywrapped_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrapped',
            name='timeframe',
            field=models.CharField(choices=[('short_term', 'Short Term'), ('medium_term', 'Medium Term'), ('long_term', 'Long Term')], default='medium_term', max_length=20),
        ),
        migrations.AddField(
            model_name='spotifywrapped',
            name='top_genres',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotifywrapped',
            name='top_artists',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotifywrapped',
            name='top_tracks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
