# Generated by Django 5.1.1 on 2024-11-19 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_spotifywrapped_timeframe_spotifywrapped_top_genres_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifywrapped',
            name='timeframe',
        ),
        migrations.AddField(
            model_name='spotifywrapped',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
