# Generated by Django 5.1.1 on 2024-11-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_spotifywrapped_timeframe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifywrapped',
            name='presentation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
