# Generated by Django 5.1.1 on 2024-09-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_finder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_google_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_locations",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="food_finder.foodlocation"
            ),
        ),
    ]
